#! /usr/bin/bash
if test "Ketch" = $HOSTNAME ; then
   echo "Ketch doesn't use cifs mounts."
elif test "Square-Rigger" = $HOSTNAME ; then
   mount-KE
   mount-EX
elif test "Excalibur" = $HOSTNAME ; then
   mount-KE
   mount-SR
else
   echo "Can't mount anything because this is an unknown computer."
fi
