#! /usr/bin/bash
if test "Excalibur" = $HOSTNAME ; then
   umount-SR
   umount-KE
   umount-AV
elif test "Square-Rigger" = $HOSTNAME ; then
   umount-EX
   umount-KE
   umount-AV
elif test "Ketch" = $HOSTNAME ; then
   echo "Error in disnet: Ketch doesn't use cifs mounts."
elif test "Avalon" = $HOSTNAME ; then
   umount-EX
   umount-SR
   umount-KE
else
   echo "Can't umount anything because this is an unknown computer."
fi
