#! /usr/bin/bash
if test "Ketch" = $HOSTNAME ; then
   echo "Ketch doesn't use cifs mounts."
elif test "Square-Rigger" = $HOSTNAME ; then
   umount-KE
   umount-EX
elif test "Excalibur" = $HOSTNAME ; then
   umount-KE
   umount-SR
else
   echo "Can't umount anything because this is an unknown computer."
fi
