@echo off
rem killrstr.bat
rem _RESTORE killer
rem Author: Robbie
rem Date written: Sunday January 18, 2004
rem Last updated: Thursday February 26, 2004

c:
cd \
call datini _restore
deltree /y _restore

d:
cd \
call datini _restore
deltree /y _restore

e:
cd \
call datini _restore
deltree /y _restore

f:
cd \
call datini _restore
deltree /y _restore

g:
cd \
call datini _restore
deltree /y _restore

h:
cd \
call datini _restore
deltree /y _restore

i:
cd \
call datini _restore
deltree /y _restore

c:
cd \

