@echo off
rem trshempt.bat
rem Recycle-bin emptier
rem Author: Robbie Hatley
rem Date written: Sunday January 18, 2004
rem Last updated: Thursday February 26, 2004

c:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

d:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

e:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

f:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

g:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

h:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

i:
cd \
call datini recycled
deltree /y recycled
md "Recycled"

c:
cd \

