/* This is a 79-character-wide ASCII C source-code text file (LF=0x0D0A).    */
/*=======|=========|=========|=========|=========|=========|=========|=======*/

/*****************************************************************************\
 * Program name:  Treadmill Power
 * Description:   Calculates available generated power from a user on a
 *                cordless treadmill at various speeds, grades, and weights.
 * File name:     treadmill-power.c
 * Source for:    treadmill-power.exe
 * Inputs:        none
 * Outputs:       4D power chart (P=f(s,g,w))
 * Author:        Robbie Hatley
 * Edit history:
 *    Wed May 23, 2018: Wrote it.
\*****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// Convert lbf to N (definition of lbf in terms of N):
#define LBF_TO_N(X) (4.44822162*X)

// Convert miles/hour to meters/second (from unit equation):
// (1mi/1hr)(5280ft/1mi)(12in/1ft)(2.54cm/1in)(1m/100cm)(1hr/3600s)=0.44704m/s
#define MPH_TO_MPS(X) (0.44704*X)

// Convert Percent Grade to Sine(alpha):
#define PG_TO_SA(X) ((X/100.0)/sqrt(1+(X/100.0)*(X/100.0)))

// Calculate power at given speed, weight, grade:
double UserGeneratedPower 
   (
      double LBF, // Weight of user in avoirdupois pounds.
      double MPH, // Speed of user in miles per hour.
      double PG   // Percent Grade of tread
   )
{
   double Weight, Speed, SineAlpha, Power ;
   Weight    = LBF_TO_N(LBF);
   Speed     = MPH_TO_MPS(MPH);
   SineAlpha = PG_TO_SA(PG);
   Power     = Weight * Speed * SineAlpha;
   return Power;
}

int main(void)
{
   double LBF, MPH, PG, PWR;

   for ( MPH = 1.0 ; MPH <= 10.0 ; MPH += 0.5 )
   {
      // Print column headings for this page:
      printf("Power In Watts Generated By User For Speed = %fMPH\n", MPH);
      printf("(columns = user weight in LB; rows = percent grade)\n");
      printf(" PG |    75   100   125   150   175   200   225   250   275   300\n");
      printf("-----------------------------------------------------------------\n");
      for ( PG = 1.0 ; PG <= 20.0 ; PG += 1.0 )
      {
         printf(" %2.0f |", PG);
         for ( LBF = 75.0 ; LBF <= 300.0 ; LBF += 25.0 )
         {
            PWR = UserGeneratedPower(LBF, MPH, PG);
            printf("%6.0f", PWR);
         }
         printf("\n");
      }
      printf("\n\n");
   }
   return 0;
}
