renamefiles -d -r -q -y "[ -]+\(" "("
renamefiles -d -r -q -y "\)[ -]+" ")"
renamefiles -d -r -q -y "&" "-And-"
renamefiles -d -r -q -y ", " "-"
renamefiles -d -r -q -y " " "-"
renamefiles -d -r -q -y "--+" "-"
